parameters:
    pim_api.normalizer.exception.documented.class: Pim\Component\Api\Normalizer\Exception\DocumentedNormalizer
    pim_api.normalizer.exception.violation.class: Pim\Component\Api\Normalizer\Exception\ViolationNormalizer

services:
    fos_rest.serializer:
        class: FOS\RestBundle\Serializer\SymfonySerializerAdapter
        arguments:
            - '@pim_external_api_exception_serializer'

    fos_rest.serializer.exception_normalizer.symfony:
        class: FOS\RestBundle\Serializer\Normalizer\ExceptionNormalizer
        arguments:
            - '@fos_rest.exception.messages_map'
            - false
        tags:
            - { name: pim_external_api_exception_serializer.normalizer, priority: 90 }

    pim_api.normalizer.exception.documented:
        class: '%pim_api.normalizer.exception.documented.class%'
        tags:
            - { name: pim_external_api_exception_serializer.normalizer, priority: 100 }

    pim_api.normalizer.exception.violation:
        class: '%pim_api.normalizer.exception.violation.class%'
        tags:
            - { name: pim_external_api_exception_serializer.normalizer, priority: 100 }
