category:
    resource: '@PimApiBundle/Resources/config/routing/category.yml'
    prefix: /rest/v1/categories

family:
    resource: '@PimApiBundle/Resources/config/routing/family.yml'
    prefix: /rest/v1/families
