config:
    config:
        pim/fetcher-registry:
            fetchers:
                ui-locale:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: pim_localization_locale_index
        oro/form/system/config/save:
            route: oro_config_configuration_system_post

    paths:
        # Forms
        oro/form/system/config/tab/localization: oroconfig/js/form/system/tab/localization
        oro/form/system/config/tab/notification: oroconfig/js/form/system/tab/notification
        oro/form/system/config/save:             oroconfig/js/form/system/save
        oro/form/system/config:                  oroconfig/js/form/system/config


        # Templates
        oro/template/system/group/localization: oroconfig/js/templates/system/group/localization.html
        oro/template/system/group/notification: oroconfig/js/templates/system/group/notification.html
        oro/template/system/config:             oroconfig/js/templates/system/config.html
