parameters:
    pim_datagrid.repository.datagrid_view.class: Pim\Bundle\DataGridBundle\Repository\DatagridViewRepository
    pim_datagrid.entity.datagrid_view.class: Pim\Bundle\DataGridBundle\Entity\DatagridView

services:
    pim_datagrid.repository.datagrid_view:
        class: '%pim_datagrid.repository.datagrid_view.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_datagrid.entity.datagrid_view.class%'
