parameters:
    akeneo_file_storage.repository.file_info.class: Akeneo\Bundle\FileStorageBundle\Doctrine\ORM\Repository\FileInfoRepository

services:
    akeneo_file_storage.repository.file_info:
        class: '%akeneo_file_storage.repository.file_info.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%akeneo_file_storage.model.file_info.class%'
