parameters:
    pim_user.repository.role.class:  Pim\Bundle\UserBundle\Doctrine\ORM\Repository\RoleRepository
    pim_user.repository.group.class: Pim\Bundle\UserBundle\Doctrine\ORM\Repository\GroupRepository
    pim_user.repository.user.class:  Pim\Bundle\UserBundle\Doctrine\ORM\Repository\UserRepository

services:
    pim_user.repository.role:
        class: '%pim_user.repository.role.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_user.entity.role.class%'

    pim_user.repository.group:
        class: '%pim_user.repository.group.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_user.entity.group.class%'

    pim_user.repository.user:
        class: '%pim_user.repository.user.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_user.entity.user.class%'
