parameters:
    pim_notification.repository.user_notification.class: Pim\Bundle\NotificationBundle\Entity\Repository\UserNotificationRepository

services:
    pim_notification.repository.user_notification:
        class: '%pim_notification.repository.user_notification.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_notification.entity.user_notification.class%'
