parameters:
    pim_comment.repository.comment.class: Pim\Bundle\CommentBundle\Repository\CommentRepository

services:
    pim_comment.repository.comment:
        class: '%pim_comment.repository.comment.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_comment.entity.comment.class%'
